"""Initial migration

Revision ID: 2882ac5c88b9
Revises: 
Create Date: 2026-07-09 10:46:09.133147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2882ac5c88b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('idx_ticket_assigned_status', ['assigned_to_id', 'status'], unique=False)
        batch_op.create_index('idx_ticket_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_ticket_customer_status', ['customer_id', 'status'], unique=False)
        batch_op.create_index('idx_ticket_priority', ['priority'], unique=False)
        batch_op.create_index('idx_ticket_sla_resolution', ['sla_resolution_due_at', 'sla_resolution_breached'], unique=False)
        batch_op.create_index('idx_ticket_sla_response', ['sla_response_due_at', 'sla_response_breached'], unique=False)
        batch_op.create_index('idx_ticket_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('idx_ticket_status')
        batch_op.drop_index('idx_ticket_sla_response')
        batch_op.drop_index('idx_ticket_sla_resolution')
        batch_op.drop_index('idx_ticket_priority')
        batch_op.drop_index('idx_ticket_customer_status')
        batch_op.drop_index('idx_ticket_created_at')
        batch_op.drop_index('idx_ticket_assigned_status')

    # ### end Alembic commands ###
