"""Initial migration

Revision ID: f3e2ccf2d6d3
Revises: 
Create Date: 2026-07-09 10:47:28.594372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e2ccf2d6d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_project_id', 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key('fk_tasks_assigned_to_id', 'users', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_assigned_to_id', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_project_id', type_='foreignkey')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
